In [1]:
#Q1
import numpy as np

# Defining the spot rates
s = np.array([525, 550, 575, 600, 625]) / 1e4

# Calculations for the first set of cash flows
pv1 = np.array([6] * 4 + [106]) / (1 + s) ** np.arange(1, 6)
P1 = np.sum(pv1)
dP1dlambda = np.array([6] * 4 + [106]) * np.arange(1, 6) * (1 + s) ** -np.arange(2, 7)
D1 = np.sum(dP1dlambda) / P1

# Calculations for the second set of cash flows
pv2 = np.array([10] * 3 + [110]) / (1 + s[:4]) ** np.arange(1, 5)
P2 = np.sum(pv2)
dP2dlambda = np.array([10] * 3 + [110]) * np.arange(1, 5) * (1 + s[:4]) ** -np.arange(2, 6)
D2 = np.sum(dP2dlambda) / P2

# Calculations for the observed cash flows
ob = np.array([50000, 102000, 104000, 106000, 54000])
P_ob = np.sum(ob / (1 + s) ** np.arange(1, 6))
D_ob = np.sum(ob * np.arange(1, 6) * (1 + s) ** -np.arange(2, 7)) / P_ob

# Solving the linear equations
x = np.round(np.linalg.solve([[P1, P2], [P1 * D1, P2 * D2]], [P_ob, P_ob * D_ob]), 3)

print("x:", x)

x: [-2216.56   5003.967]


In [ ]:
#Q2
def investment_value_after_mortgage(P, r_mortgage, r_investment, term_years):
    m = 12  # monthly compounding and payments
    term_months = term_years * m

    # Monthly mortgage payment calculation
    monthly_payment = r_mortgage / m * P / (1 - (1 + r_mortgage / m) ** -term_months)

    # Initial investment amount
    investment_value = P  # same as the mortgage amount

    for _ in range(term_months):
        # Increase investment by monthly growth rate
        investment_value *= (1 + r_investment / m)
        
        # Subtract monthly mortgage payment
        investment_value -= monthly_payment

    return round(investment_value)

# Mortgage and investment details
P = 500000  # Principal amount of the mortgage
r_mortgage = 0.06  # Annual interest rate of the mortgage
r_investment = 0.01 * 12  # Monthly growth rate of the S&P 500 investment, converted to annual rate
term_years = 30  # Term of the mortgage in years

investment_value_after_mortgage(P, r_mortgage, r_investment, term_years)

In [2]:
#Q3
import numpy as np

# Parameters
interest_rate = 0.06

# Initialize the array A
A = np.zeros(49)

# Loop to calculate NPV for each case
for i in range(2, 51):
    a = [2000] + [2000 + j * 1000 for j in range(1, i)] + [2000 + i * 1000 + 26000]
    b = [26000] + a * 50
    npv = np.sum(b / np.power(1 + interest_rate, np.arange(len(b))))
    A[i - 2] = npv

# Finding the minimum NPV and corresponding index
min_value = np.min(A)
min_index = np.argmin(A) + 2  # adding 2 to match the MATLAB indexing

# Adjusting for MATLAB's 1-based indexing
adjusted_min_index = min_index + 1

# Output the result
adjusted_min_index

8

In [3]:
#Q4
def allocate_a(n, rb, rm, rf):   # $n dollars, a in market portfolio, n-a in risk-free asset, return a
    # n*rb = a*rm + (n-a)*rf
    return n*(rb-rf) / (rm-rf)

allocate_a(n=1000, rb=0.2, rm=0.16, rf=0.06)

1400.0

In [6]:
# Q5
import numpy as np

# Covariance matrix V
V = np.array([
    [0.21, 0.12, 0.17, 0.13, 0.16],
    [0.12, 0.15, 0.12, 0.10, 0.12],
    [0.17, 0.12, 0.19, 0.14, 0.15],
    [0.13, 0.10, 0.14, 0.15, 0.14],
    [0.16, 0.12, 0.15, 0.14, 0.21]
])

# Augmenting the covariance matrix with ones to account for the constraint
augmented_matrix = np.vstack([V, np.ones(V.shape[1])])
augmented_matrix = np.hstack([augmented_matrix, np.ones((augmented_matrix.shape[0], 1))])
augmented_matrix[-1, -1] = 0

# Right-hand side vector
b = np.zeros(V.shape[1] + 1)
b[-1] = 1

# Solving the linear system
solution = np.linalg.solve(augmented_matrix, b)

# Extracting the weights
weights = solution[:-1]

weights, np.dot(weights.T, np.dot(V, weights))


(array([ 0.0971984 ,  0.53230417, -0.15208691,  0.60777587, -0.08519154]),
 0.12381360777587194)

In [24]:
#Q6
import numpy as np

# Define the variables
var_v = 0.04
beta = np.array([1.16, 0.70, 1.15, 0.98, 1.01]).reshape(-1, 1)  # Reshape to column vector
cov_v = 2*beta * var_v

# Define the matrix V
V = np.array([[0.21, 0.12, 0.17, 0.13, 0.16],
              [0.12, 0.15, 0.12, 0.10, 0.12],
              [0.17, 0.12, 0.19, 0.14, 0.15],
              [0.13, 0.10, 0.14, 0.15, 0.14],
              [0.16, 0.12, 0.15, 0.14, 0.21]])

# Construct the matrix and vector for the linear system
A = np.block([[2 * V, -np.ones((5, 1))],
              [np.ones((1, 5)), np.zeros((1, 1))]])
b = np.vstack([2 * cov_v, [[1]]])

# Solve the linear system
OPW_12 = np.linalg.solve(A, b)

# Print the result
print(OPW_12)

[[ 0.23432819]
 [ 0.15764437]
 [ 0.13781589]
 [ 0.52594626]
 [-0.05573471]
 [ 0.11642081]]


In [11]:
#Q7
import numpy as np

# Define the variables
var_v = 0.04
beta = np.array([1.16, 0.70, 1.15, 0.98, 1.01]).reshape(-1, 1)  # Reshape to column vector
cov_v = 2*beta * var_v

# Define the matrix V
V = np.array([[0.21, 0.12, 0.17, 0.13, 0.16],
              [0.12, 0.15, 0.12, 0.10, 0.12],
              [0.17, 0.12, 0.19, 0.14, 0.15],
              [0.13, 0.10, 0.14, 0.15, 0.14],
              [0.16, 0.12, 0.15, 0.14, 0.21]])

# Construct the matrix and vector for the linear system
A = np.block([[2 * V, -np.ones((5, 1))],
              [np.ones((1, 5)), np.zeros((1, 1))]])
b = np.vstack([2 * cov_v, [[1]]])

# Solve the linear system
OPW_12 = np.linalg.solve(A, b)

# Print the result
print(OPW_12)

[[ 0.23432819]
 [ 0.15764437]
 [ 0.13781589]
 [ 0.52594626]
 [-0.05573471]
 [ 0.11642081]]


In [14]:
#Q7
import numpy as np

def IRRPoly(cash_flow, m):
    coefficients = np.flip(cash_flow)
    roots = np.roots(coefficients)
    irr_poly = np.real(roots[(roots >= 0)  & (np.iscomplex(roots) == False)])[0]
    irr = m*(1 - irr_poly) / irr_poly
    return irr

# Bond characteristics
face_value = 100
coupon_payment = 4  #yearly
payments_per_year = 2
years_to_maturity = 5
current_price = 110

# Cash flows for the bond

cash_flows = (coupon_payment / payments_per_year)*np.ones(years_to_maturity * payments_per_year)
cash_flows[-1] += face_value
print(cash_flows)
cash_flows = np.insert(cash_flows, 0, -current_price)
print(cash_flows)

# Find YTM using IRRPoly function
ytm = IRRPoly( cash_flows, payments_per_year)

# Convert to a percentage and display the result
ytm_percentage = ytm * 100
print(f"The bond's yield to maturity is {ytm_percentage:.2f}%")

def bond_price(F, C, lamb, m, n):
    '''
    F is the face value of the bond
    C is the yearly coupon payment
    lamb is the yield of the bond 
    m is the number of coupon payments per year
    n is the number of coupon payments remaning
    '''
    r = lamb / m  # Semi-annual yield
    discount_factor = (1 + r) ** n
    bond_price = (C / r) * (1 - 1 / discount_factor) + F / discount_factor
    return bond_price

face_value = 100
coupon_rate = 0.1
periods=10
frequency = 1
yield_to_maturities = ytm_percentage
coupon_payment_per_period = face_value * coupon_rate / frequency
bond_price(face_value, coupon_payment_per_period, ytm, frequency, periods * frequency)

[  2.   2.   2.   2.   2.   2.   2.   2.   2. 102.]
[-110.    2.    2.    2.    2.    2.    2.    2.    2.    2.  102.]
The bond's yield to maturity is 1.89%


173.21395912251086

In [16]:
#Q8 it is max sharpe
import numpy as np

# Number of assets
n_assets = 100

# Variance of each asset (assumed to be the same for all assets)
variance = 1  # Since actual variance is not provided, we use a placeholder value

# Sharpe ratios for each asset
sharpe_ratios = np.array([k/100 for k in range(1, n_assets+1)])

# Since all assets have the same variance, the weight of each asset in the
# optimal portfolio is proportional to its Sharpe ratio
weights = sharpe_ratios / np.sum(sharpe_ratios)

# The asset with the maximum Sharpe ratio has the highest weight
max_sharpe_ratio_weight = weights[-1]  # Last asset has the highest Sharpe ratio

# Convert to percentage and round to two decimal places
max_sharpe_ratio_weight_percent = round(max_sharpe_ratio_weight * 100, 2)

print(f"The optimal portfolio weight for the asset with the maximum Sharpe ratio is {max_sharpe_ratio_weight_percent}%")


The optimal portfolio weight for the asset with the maximum Sharpe ratio is 1.98%


In [18]:
#Q8 it is min sharpe(right answer)
import numpy as np

# Number of assets
n_assets = 100

# Sharpe ratios for each asset
sharpe_ratios = np.array([k/100 for k in range(1, n_assets+1)])

# Since all assets have the same variance, the weight of each asset in the
# optimal portfolio is proportional to its Sharpe ratio
weights = sharpe_ratios / np.sum(sharpe_ratios)

# The weight of the asset with the minimum Sharpe ratio (first asset)
min_sharpe_ratio_weight = weights[0]

# Convert to percentage and round to two decimal places
min_sharpe_ratio_weight_percent = round(min_sharpe_ratio_weight * 100, 6)

print(f"The optimal portfolio weight for the asset with the minimum Sharpe ratio is {min_sharpe_ratio_weight_percent}%")


The optimal portfolio weight for the asset with the minimum Sharpe ratio is 0.019802%


In [19]:
#Q9
import numpy as np

C = 0
F = 1
lambda_ = np.array([3.1, 3, 2.9, 2.5, 2.5, 1]) * 0.01
m = 1
n = np.array([30, 25, 20, 15, 10, 5])

P = F / ((1 + lambda_ / m) ** n)

# Iterating through the first five elements to calculate the ratio
for i in range(5):
    print(P[i + 1] / P[i])

# Calculating the specific value as per the last line of your code
result = 100000 * P[3] / P[2] * P[3] / P[2]
print("Result:", result)


1.1935190104692306
1.1820153661193291
1.223064932600826
1.1314082128906244
1.217956521038558
Result: 149588.7829357863


In [20]:
#Q10
import cvxpy as cp

# Given data
V = np.array([ # covariance matrix
    [0.21, 0.12, 0.17, 0.13, 0.16],
    [0.12, 0.15, 0.12, 0.10, 0.12],
    [0.17, 0.12, 0.19, 0.14, 0.15],
    [0.13, 0.10, 0.14, 0.15, 0.14],
    [0.16, 0.12, 0.15, 0.14, 0.21]
])
r_bar = np.array([0.69, 0.65, 0.44, 0.36, 0.41]) # expected returns

# The variable we are solving for
weights = cp.Variable(5)

# The objective is to minimize the portfolio variance
# and maximize the expected return
risk = cp.quad_form(weights, V)
return_portfolio = r_bar @ weights
objective = cp.Minimize(risk - return_portfolio)

# The sum of the weights must be 1
constraints = [cp.sum(weights) == 1]

# Solving the problem
prob = cp.Problem(objective, constraints)
prob.solve()

# The optimal weights
optimal_weights = weights.value

# Output the optimal weights
print("The optimal weights for the portfolio are:")
print(optimal_weights)

The optimal weights for the portfolio are:
[ 2.39308176  1.81446541 -1.7327044  -0.46855346 -1.00628931]


In [3]:
#Q11 不一定对
initial_investment = 200  # SVB's investment in the bond in billion dollars
coupon_rate = 6  # Annual coupon rate in percent
face_value_bond = 100  # Standard face value of the bond (assumed to be 100)
withdrawal_requests = 180  # Clients' withdrawal requests in billion dollars

# New spot rates (after one year) in percent
spot_rates = {1: 11.25, 2: 11.50, 3: 11.75, 4: 12.00, 5: 12.25}

# The bond has 4 years and 4 coupon payments remaining
# Annual coupon payment (in billion dollars)
annual_coupon_payment = (coupon_rate / 100) * initial_investment

# Present value of future cash flows from the bond
# PV = C/(1+r1) + C/(1+r2)^2 + C/(1+r3)^3 + C/(1+r4)^4 + (F+C)/(1+r4)^4
# C is the annual coupon payment and F is the face value of the bond
# The face value is scaled by the initial investment amount
present_value_bond = sum([annual_coupon_payment / ((1 + spot_rates[year]/100) ** year) for year in range(1, 5)])
present_value_bond += (annual_coupon_payment + (face_value_bond / 100 * initial_investment)) / ((1 + spot_rates[4]/100) ** 4)

# Total cash after receiving the first coupon payment and selling the bond
total_cash = annual_coupon_payment + present_value_bond

# Calculating the shortfall and the required bailout amount
shortfall = withdrawal_requests - total_cash
shortfall_billion = round(shortfall)  # rounding to nearest integer
print(shortfall)
shortfall_billion, present_value_bond, total_cash

-3.3936978629236023


(-3, 171.3936978629236, 183.3936978629236)

In [7]:
# Parameters
initial_investment = 200  # SVB's investment in the bond (in billion dollars)
coupon_rate = 6  # Annual coupon rate (in percent)
withdrawal_requests = 180  # Total withdrawal requests (in billion dollars)

# Original and increased spot rates
original_spot_rates = [5.25, 5.50, 5.75, 6.00, 6.25]  # in percent
increased_spot_rates = [rate + 6 for rate in original_spot_rates]  # in percent

# The bond has 4 years and 4 coupon payments remaining
annual_coupon_payment = initial_investment * (coupon_rate / 100)  # in billion dollars

# Present value of future cash flows from the bond
# First year's coupon is discounted at the original rate (5.25%)
# Remaining coupons and face value are discounted at the increased rates
present_value_coupons = annual_coupon_payment / (1 + original_spot_rates[0] / 100)
present_value_coupons += sum([annual_coupon_payment / ((1 + increased_spot_rates[year] / 100) ** (year + 1)) for year in range(1, 4)])
present_value_face_value = initial_investment / ((1 + increased_spot_rates[3] / 100) ** 4)

# Total present value of the bond
present_value_bond = present_value_coupons + present_value_face_value

# Total cash after selling the bond and receiving the first coupon payment
total_cash_available = present_value_bond + annual_coupon_payment

# Calculating the shortfall and the required bailout amount
shortfall = withdrawal_requests - total_cash_available
bailout_needed = max(shortfall, 0)  # Ensuring bailout amount is not negative

# Results
shortfall, bailout_needed, present_value_coupons,present_value_bond, total_cash_available


(3.617610753719674,
 3.617610753719674,
 37.27877356531412,
 164.38238924628033,
 176.38238924628033)

In [2]:
# Given data:
initial_investment = 200  # in billion dollars
annual_coupon_rate = 0.06  # 6%
coupon_payment = annual_coupon_rate * initial_investment  # Coupon payment received on March 1, 2023
years_remaining = 4  # 4 years remaining after the first coupon
withdrawal_request = 180  # in billion dollars

# New spot rate curve (after +6% increase across all maturities):
spot_rates = {
    1: 0.1125,  # 11.25%
    2: 0.1150,  # 11.50%
    3: 0.1175,  # 11.75%
    4: 0.1200   # 12.00%
}

# Calculate the present value of the remaining cash flows of the bond
present_value_bond = 0
for year in range(1, years_remaining + 1):
    cash_flow = coupon_payment if year < years_remaining else coupon_payment + initial_investment
    discount_factor = 1 / (1 + spot_rates[year]) ** year
    present_value_bond += cash_flow * discount_factor

# Calculate the total cash SVB has after selling the bond and receiving the coupon payment
total_cash = present_value_bond + coupon_payment

# Calculate the amount of bailout money needed
bailout_needed = withdrawal_request - total_cash
bailout_needed_billion = round(bailout_needed)
print(bailout_needed)
bailout_needed_billion


4.232519077934342


4

(81.31946596893047, 174638931937.86093, 5361068062.139069, 3000000000.0)