In [1]:
payments_to_go=5
original_interest_rate = 0.08
original_monthly_payment=10000

def calculate_remaining_balance(A, r, n):
    remaining_balance = (A/r)*(1-1/(1+r)**n)
    return remaining_balance

remaining_balance = calculate_remaining_balance(original_monthly_payment, original_interest_rate, payments_to_go)
print(f'PV: ${remaining_balance:.2f}')

PV: $39927.10


In [2]:
payments_to_go=6
original_interest_rate = 0.08
original_monthly_payment=10000

def calculate_remaining_balance(A, r, n):
    remaining_balance = (A/r)*(1-1/(1+r)**n)
    return remaining_balance

remaining_balance = calculate_remaining_balance(original_monthly_payment, original_interest_rate, payments_to_go)
print(f'PV: ${remaining_balance:.2f}')

PV: $46228.80


In [4]:
def calculate_npv(happiness_scores, interest_rate):
    npv = 0
    for i, score in enumerate(happiness_scores):
        npv += score / (1 + interest_rate) ** i
    return npv

# Define the happiness scores for each career path
career_A = [0,0.93,0.85,0.76,0.66,0.56,0.46,0.36,0.26,0.16,0.09,0.04]

# Define the discount rate
discount_rate = 0.08

# Calculate the NPV of happiness scores for both career paths
npv_A = calculate_npv(career_A, discount_rate)

# Print the results
print(f"expected present value of the annuity: {npv_A*10000:.2f}")

expected present value of the annuity: 38386.95


In [1]:
#3.9-1
payments_to_go=4
original_interest_rate = 0.1
#original_monthly_payment=22847
PV=22487

def calculate_remaining_balance(p, r, n):
    remaining_balance =(p*r*(1+r)**n)/(((1+r)**n)-1)
    return remaining_balance

remaining_balance = calculate_remaining_balance(PV, original_interest_rate, payments_to_go)
print(f'A: ${remaining_balance:.2f}')

A: $7093.99


In [18]:
#3.9-2
payments_to_go=6
original_interest_rate = 0.1
#original_monthly_payment=22847
PV=37582

def calculate_remaining_balance(p, r, n):
    remaining_balance =(p*r*(1+r)**n)/(((1+r)**n)-1)
    return remaining_balance

remaining_balance = calculate_remaining_balance(PV, original_interest_rate, payments_to_go)
print(f'A: ${remaining_balance:.2f}')

A: $8629.10


In [19]:
#3.10
def calculate_monthly_payment(P, r, n):
    return P * r * (1 + r)**n / ((1 + r)**n - 1)

def calculate_remaining_balance(A, r, n):
    remaining_balance = (A/r)*(1-1/(1+r)**n)
    return remaining_balance

# (a) Original yearly payment
P = 100000  # Principal
r = 0.08   # Initial interest rate
n = 30     # 30 years

original_payment = calculate_monthly_payment(P, r, n)
print(f"(a) Original yearly payment: ${original_payment:.2f}")
new_n=n-5
# (b) Remaining balance after 5 years
remaining_balance_5_years = calculate_remaining_balance(original_payment, r, new_n)
print(f"(b) Remaining balance after 5 years: ${remaining_balance_5_years:.2f}")

# (c) New yearly payment after 5 years with 9% interest rate
r_new = 0.09
new_payment = calculate_monthly_payment(remaining_balance_5_years, r_new, new_n)
print(f"(c) New yearly payment after 5 years with 9% interest rate: ${new_payment:.2f}")


(a) Original yearly payment: $8882.74
(b) Remaining balance after 5 years: $94821.30
(c) New yearly payment after 5 years with 9% interest rate: $9653.40


[3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0,

In [26]:
pip install gekko

     ---------------------------------------- 12.2/12.2 MB 3.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [35]:
#3.11-1
from scipy import linalg
import numpy as np

A = np.array([[1000, 1000, 1000], [4, 4, 8], [0, 1, -1]])  # A代表系数矩阵
b = np.array([1000, 0, 0])  # b代表常数列
x = linalg.solve(A, b)
#print(x)
y=np.array([950,1100,900])
print(x*y)

[ 3. -1. -1.]
[ 2850. -1100.  -900.]


In [36]:
#3.11-2
from scipy import linalg
import numpy as np

A = np.array([[1000, 1000, 1000], [4, 4, 8], [0, 1, -1]])  # A代表系数矩阵
b = np.array([1000, 0, 1])  # b代表常数列
x = linalg.solve(A, b)
#print(x)
y=np.array([950,1100,900])
print(x*y)

[1900.    0. -900.]
