In [13]:
#Q3
import numpy as np

# Data for stocks and index
Index = np.array([12.3, 5.5, 4.3, 6.7, 9.7, 8.3, 5.6, 5.7, 5.7, 3.6])
Stock_1 = np.array([11.91, 18.37, 3.64, 24.37, 30.42, -1.45, 20.11, 9.28, 17.63, 15.71])
Stock_2 = np.array([29.59, 15.25, 3.53, 17.67, 12.74, -2.56, 25.46, 6.92, 9.73, 25.09])
Stock_3 = np.array([23.27, 19.47, -6.58, 15.08, 16.24, -15.05, 17.80, 18.82, 3.05, 16.94])
Stock_4 = np.array([27.24, 17.05, 10.20, 20.26, 19.84, 1.51, 12.24, 16.12, 22.93, 3.49])

# Calculate the Market as the average of the four stocks
Market = (Stock_1 + Stock_2 + Stock_3 + Stock_4) / 4

# Create a matrix R of the stock data
R = np.vstack([Stock_1, Stock_2, Stock_3, Stock_4]).T

# Calculate the covariance matrix of R
cov_R = np.cov(R.T)  # Transpose R to get stocks as variables (columns)

# Calculate the eigenvalues and eigenvectors of the covariance matrix
eigenvalues, eigenvectors = np.linalg.eig(cov_R)

# Extract the principal component
# The eigenvector corresponding to the largest eigenvalue is the principal component
largest_eigenvalue_index = np.argmax(eigenvalues)
principal_component = eigenvectors[:, largest_eigenvalue_index]

# Normalize the principal component
normalized_principal_component = principal_component / np.sum(principal_component)

# Calculate the principal component scores for each stock
PC_scores = R.dot(normalized_principal_component)

# Print the covariance matrix
print("Covariance matrix (R):\n", cov_R)

eigenvalues, eigenvectors = np.linalg.eig(cov_R)

# Eigenvalues (D)
D = eigenvalues

# Print the eigenvalues
print("Eigenvalues (D):", D)

# Identify the eigenvector associated with the largest eigenvalue
largest_eigenvalue_index = np.argmax(eigenvalues)
principal_eigenvector = eigenvectors[:, largest_eigenvalue_index]

# Normalize this eigenvector
P = principal_eigenvector / np.sum(principal_eigenvector)
print("Normalized Principal Eigenvector (P):",P)

# Calculate the principal component scores (PC)
PC = R.dot(P)

# Construct the final array including the transposed stock data, market data, and principal component scores
final_array = np.column_stack([R, Market, PC])
print("Combined Array (Stock Data, Market Average, PC):\n",final_array)

Covariance matrix (R):
 [[ 90.26465444  50.89496889  79.02409333  40.17989778]
 [ 50.89496889 107.22566222 105.37893556  30.98590444]
 [ 79.02409333 105.37893556 162.20478222  56.53679778]
 [ 40.17989778  30.98590444  56.53679778  68.25477333]]
Eigenvalues (D): [311.16736846  58.05278743  36.97666605  21.75305028]
Normalized Principal Eigenvector (P): [0.21864157 0.26507102 0.36204532 0.15424208]
Combined Array (Stock Data, Market Average, PC):
 [[ 11.91        29.59        23.27        27.24        23.0025
   23.07382172]
 [ 18.37        15.25        19.47        17.05        17.535
   17.73762871]
 [  3.64         3.53        -6.58        10.2          2.6975
    0.92256705]
 [ 24.37        17.67        15.08        20.26        19.345
   18.59668812]
 [ 30.42        12.74        16.24        19.84        19.81
   18.96786036]
 [ -1.45        -2.56       -15.05         1.51        -4.3875
   -6.21148867]
 [ 20.11        25.46        17.8         12.24        18.9025
   19.4779201 ]
 

In [15]:
#Q5
import numpy as np

r = np.array([2, 34, 12, 34, 67, 11, 33, 56, 34, -28]) / 100
F = np.array([40, 80, 14, 66, 90, 20, 18, 47, 21, -30]) / 100
A = np.vstack((np.ones(10), F)).T

# Compute the answer_8_5 using matrix operations
answer_8_5 = np.linalg.inv(np.dot(A.T, A)).dot(A.T).dot(r)
print(answer_8_5)

# Compute B, b, and a
B = np.cov(r, F, rowvar=False) / np.var(F, ddof=1)
b = B[1, 0]
a = np.mean(r) - np.mean(F) * b

# Output results
print("B matrix:")
print(B)
print("b value:", b)
print("a value:", a)

[0.0356933  0.59919864]
B matrix:
[[0.58389128 0.59919864]
 [0.59919864 1.        ]]
b value: 0.5991986401165613
a value: 0.03569329771733856
