In [1]:
#Q1 
#this year
# Constants and initial values
# Function to calculate the after-tax present value of the vaccine project
def calculate_npv(initial_investment, sales_per_unit, units_sold_annually, wage_rate_per_hour, 
                  hours_of_labor_annually, cost_per_ton_raw_material, tons_of_raw_material_annually, 
                  inflation_rate, corporate_tax_rate, depreciation, interest_rate, years):
    # Initialize list to hold the cash flows
    cash_flows = []

    # Calculate the cash flows for each year
    for year in range(1, years + 1):
        # Adjust for inflation
        sales = sales_per_unit * (1 + inflation_rate) ** (year - 1) * units_sold_annually
        labor_cost = wage_rate_per_hour * (1 + inflation_rate) ** (year - 1) * hours_of_labor_annually
        material_cost = cost_per_ton_raw_material * (1 + inflation_rate) ** (year - 1) * tons_of_raw_material_annually
        operating_income = sales - (labor_cost + material_cost)
        profit_before_tax = operating_income - depreciation
        tax = profit_before_tax * corporate_tax_rate
        profit_after_tax = profit_before_tax - tax
        cash_flow = profit_after_tax + depreciation # Add back depreciation as it's a non-cash charge
        cash_flows.append(cash_flow)
    
    # Calculate the present value of the cash flows
    npv = -initial_investment
    for i, cash_flow in enumerate(cash_flows, start=1):
        npv += cash_flow / (1 + interest_rate) ** i
    
    # Return the NPV rounded to the nearest dollar
    return round(npv)

# Define the parameters based on the provided scenario
initial_investment = 10000000
sales_per_unit = 3.30
units_sold_annually = 1000000
wage_rate_per_hour = 30
hours_of_labor_annually = 10000
cost_per_ton_raw_material = 100
tons_of_raw_material_annually = 100
inflation_rate = 0.10  # 10% inflation rate
corporate_tax_rate = 0.34
depreciation = initial_investment / 5
interest_rate = 0.05
years = 5

# Calculate the NPV
npv = calculate_npv(initial_investment, sales_per_unit, units_sold_annually, wage_rate_per_hour, 
                    hours_of_labor_annually, cost_per_ton_raw_material, tons_of_raw_material_annually, 
                    inflation_rate, corporate_tax_rate, depreciation, interest_rate, years)

print(f"The (after-tax) present value of the new vaccine project is: ${npv}")


The (after-tax) present value of the new vaccine project is: $3279795


In [ ]:
#Q2
#2*80-100=60

In [3]:
#Q3
import math
#P = mortegage value n1 = original terms, n2= rest terms, r1 = ir1, r2 =ir2
def ext_term(P, n1, m, r1, r2, n2): 
    A1 = r1/m*P*(1-1/(1+r1/m)**(n1*m))**(-1)
    P1 = A1/(r1/m)*(1-1/(1+r1/m)**((n1-n2)*m))
    a = P1 * r2/m / A1
    b = 1 - a
    t = -math.log(b, (1+r2/m))
    return t - (n1-n2)*m

ext_term(P=1000000, n1=30, m=12, r1=0.05, r2=0.06, n2=5)

87.5845978486002

In [6]:
#Q4
import numpy as np

def IRRPoly(cash_flow, m):
    coefficients = np.flip(cash_flow)
    roots = np.roots(coefficients)
    irr_poly = np.real(roots[(roots >= 0)  & (np.iscomplex(roots) == False)])[0]
    irr = m*(1 - irr_poly) / irr_poly
    return irr

# Bond characteristics
face_value = 100
coupon_payment = 4  #yearly
payments_per_year = 2
years_to_maturity = 5
current_price = 110

# Cash flows for the bond

cash_flows = (coupon_payment / payments_per_year)*np.ones(years_to_maturity * payments_per_year)
cash_flows[-1] += face_value
print(cash_flows)
cash_flows = np.insert(cash_flows, 0, -current_price)
print(cash_flows)

# Find YTM using IRRPoly function
ytm = IRRPoly( cash_flows, payments_per_year)

# Convert to a percentage and display the result
ytm_percentage = ytm * 100
print(f"The bond's yield to maturity is {ytm_percentage:.2f}%")

def bond_price(F, C, lamb, m, n):
    '''
    F is the face value of the bond
    C is the yearly coupon payment
    lamb is the yield of the bond 
    m is the number of coupon payments per year
    n is the number of coupon payments remaning
    '''
    r = lamb / m  # Semi-annual yield
    discount_factor = (1 + r) ** n
    bond_price = (C / r) * (1 - 1 / discount_factor) + F / discount_factor
    return bond_price

face_value = 100
coupon_rate = 0.1
periods=10
frequency = 1
coupon_payment_per_period = face_value * coupon_rate / frequency
bond_price(face_value, coupon_payment_per_period, ytm, frequency, periods * frequency)

[  2.   2.   2.   2.   2.   2.   2.   2.   2. 102.]
[-110.    2.    2.    2.    2.    2.    2.    2.    2.    2.  102.]
The bond's yield to maturity is 1.89%


173.21395912251086

In [6]:
#Q5
import numpy as np

# Covariance matrix V
V = np.array([
    [0.21, 0.12, 0.17, 0.13, 0.16],
    [0.12, 0.15, 0.12, 0.10, 0.12],
    [0.17, 0.12, 0.19, 0.14, 0.15],
    [0.13, 0.10, 0.14, 0.15, 0.14],
    [0.16, 0.12, 0.15, 0.14, 0.21]
])

# Expected returns of assets
r_bar = np.array([0.69, 0.65, 0.44, 0.36, 0.41])

# Constructing the augmented matrix for the linear system
A = np.vstack([
    np.hstack([V, -r_bar[:, np.newaxis], -np.ones((5, 1))]),
    np.hstack([r_bar, [0], [0]]),
    np.hstack([np.ones(5), [0], [0]])
])

# Constructing the right-hand side of the equation
b = np.append(np.zeros(5), [0.75, 1])

# Solving the linear system
solution = np.linalg.solve(A, b)

# Extracting the weights and normalizing them to sum to 1
weights = solution[:5] / sum(solution[:5])

weights


array([ 0.62496639,  0.827042  , -0.5154326 ,  0.36035382, -0.29692961])

In [7]:
#Q6
import numpy as np

# Define the covariance matrix V and expected returns r_bar
V = np.array([
    [0.21, 0.12, 0.17, 0.13, 0.16],
    [0.12, 0.15, 0.12, 0.10, 0.12],
    [0.17, 0.12, 0.19, 0.14, 0.15],
    [0.13, 0.10, 0.14, 0.15, 0.14],
    [0.16, 0.12, 0.15, 0.14, 0.21]
])
r_bar = np.array([0.69, 0.65, 0.44, 0.36, 0.41])
r_f = 0.05

# Solve for weights of one fund
v_1 = np.linalg.solve(V, r_bar - r_f)
w_1 = v_1 / sum(v_1)

# Mean return
MR1 = r_bar.T @ w_1
Var1 = w_1.T @ V @ w_1

# Desired mean
Desired_mean = 0.8

# Find weights of portfolio with desired mean
alpha = (Desired_mean - MR1) / (r_f - MR1)
w_2 = (1 - alpha) * w_1

# Variance of portfolio (for one fund s.d. = (1 - alpha) s.d. of one fund)
Var = (1 - alpha)**2 * w_1.T @ V @ w_1
Var2 = w_2.T @ V @ w_2

w_1, MR1, Var1, w_2, MR1, Var, Var2

(array([ 1.28157942,  1.19373474, -0.96748258,  0.05252814, -0.56035972]),
 1.0236876898338392,
 0.25114891219524493,
 array([ 0.987159  ,  0.91949509, -0.74522041,  0.04046072, -0.43162689]),
 1.0236876898338392,
 0.14900967570870496,
 0.14900967570870494)

In [8]:
#Q7
V = np.array([
    [0.21, 0.12, 0.17, 0.13, 0.16],
    [0.12, 0.15, 0.12, 0.10, 0.12],
    [0.17, 0.12, 0.19, 0.14, 0.15],
    [0.13, 0.10, 0.14, 0.15, 0.14],
    [0.16, 0.12, 0.15, 0.14, 0.21]
])
r_bar = np.array([0.69, 0.65, 0.44, 0.36, 0.41]).reshape(-1, 1)
var_v = 0.09
beta = np.array([1.16, 0.70, 1.15, 0.98, 1.01]).reshape(-1, 1)
cov_v = 2*beta * var_v

# Constructing the matrices for the linear system
A = np.block([
    [2 * V, -np.ones((5, 1)), -r_bar],
    [np.ones((1, 5)), 0, 0],
    [r_bar.T, 0, 0]
])
b = np.vstack((2 * cov_v, 1, 0.2))

# Solving the linear system
OPW_13 = np.linalg.solve(A, b)
OPW_13


array([[-0.17692943],
       [-0.63607876],
       [ 0.90133767],
       [ 0.69681974],
       [ 0.21485078],
       [ 0.08692531],
       [-0.25378896]])

In [10]:
#Q8
# Invest to pay off mortgage FPQ15
# Terms!!! Make sure it in month or year!!!
def inv_payoff(int_rate,terms,growth_rate,priciple):
    M = priciple*(int_rate/(1-(1+int_rate)**(-terms)))
    PFV = M*(((1+growth_rate)**terms)-1)/growth_rate
    FV_I = priciple*(1+growth_rate)**terms
    FV = FV_I - PFV
    print(FV)
    return FV
inv_payoff(0.005,360,0.01,500000)

7497782.757885488


7497782.757885488

In [4]:
#Q9
def Cons_propo_rebal(prop_of_cash,prop_of_stock,days,initial):
    stock = prop_of_stock * initial
    cash = prop_of_cash * initial
    for i in range(days):
        Ex = ((stock)/2 + 2*(stock))/2
        stock = prop_of_stock*(Ex+cash)
        cash = prop_of_cash*(Ex+cash)
    E = stock + cash
    print(E)
    return E

Cons_propo_rebal(0.5,0.5,11,100)

365.323615365196


365.323615365196

In [12]:
#Q10
import cvxpy as cp

# Given data
V = np.array([ # covariance matrix
    [0.21, 0.12, 0.17, 0.13, 0.16],
    [0.12, 0.15, 0.12, 0.10, 0.12],
    [0.17, 0.12, 0.19, 0.14, 0.15],
    [0.13, 0.10, 0.14, 0.15, 0.14],
    [0.16, 0.12, 0.15, 0.14, 0.21]
])
r_bar = np.array([0.69, 0.65, 0.44, 0.36, 0.41]) # expected returns

# The variable we are solving for
weights = cp.Variable(5)

# The objective is to minimize the portfolio variance
# and maximize the expected return
risk = cp.quad_form(weights, V)
return_portfolio = r_bar @ weights
objective = cp.Minimize(risk - return_portfolio)

# The sum of the weights must be 1
constraints = [cp.sum(weights) == 1]

# Solving the problem
prob = cp.Problem(objective, constraints)
prob.solve()

# The optimal weights
optimal_weights = weights.value

# Output the optimal weights
print("The optimal weights for the portfolio are:")
print(optimal_weights)

# Specifically, to output the weight for Meta Platforms, Inc. (formerly Facebook, ticker META):
aapl_weight = optimal_weights[0]  # Assuming the 5th stock in the list is Meta/Facebook
print(f"The optimal weight for Inc. (aapl) is: {aapl_weight:.2f}")


The optimal weights for the portfolio are:
[ 2.39308176  1.81446541 -1.7327044  -0.46855346 -1.00628931]
The optimal weight for Inc. (aapl) is: 2.39


In [ ]:
#Q11
#有答案，问一下老师

In [14]:
#Q12 gpt生成
# Given data
total_contract_value = 700e6  # $700 million
present_day_value = 460e6    # $460 million
annual_payment = 2e6         # $2 million per year for 10 years
deferred_payment = 680e6     # $680 million deferred until end of year 10

# The present value of a series of future payments is calculated using the formula:
# PV = P/(1+r)^1 + P/(1+r)^2 + ... + P/(1+r)^n + LumpSum/(1+r)^n
# Where PV is the present value, P is the annual payment, r is the interest rate, and n is the number of years
# LumpSum is the deferred payment at the end of year 10

# We will use a numerical method to find the interest rate r that satisfies the equation for the given PV

import numpy as np
from scipy.optimize import fsolve

def present_value(r):
    pv = sum([annual_payment / (1 + r)**i for i in range(1, 11)])
    pv += deferred_payment / (1 + r)**10
    return pv - present_day_value

# Initial guess for the interest rate (it's usually a small number, so we start with something like 0.05)
initial_guess = 0.05

# Finding the interest rate
interest_rate = fsolve(present_value, initial_guess)[0]

# Converting to percentage and rounding to two decimal places
interest_rate_percentage = round(interest_rate * 100, 2)

interest_rate_percentage

4.35